namespace AdvancedCsharp.Records;
/*
 * A record IS A SPECIAL KIND OF CLASS OR STRUCT THAT'S DESIGNED TO WORK
 * WELL WITH IMMUTABLE (READ-ONLY) DATA. ITS MOST USEFUL FEATURE IS NON-
 * DESTRUCTIVE MUTATION [...] THEY ELIMINATE BOILERPLATE CODE WHILE HO-
 * NORING THE EQUALITY SEMANTICS MOST SUITABLE FOR IMMUTABLE TYPES.
 * RECORDS ARE PURELY A C# COMPILE-TIME CONSTRUCT. AT RUNTIME, THE CLR
 * SEES THEM JUST AS CLASSES OR STRUCTS.
 *
 * WRITING IMMUTABLE TYPES (WHOSE FIELDS CANNOT BE MODIFIED AFTER INITI-
 * ALIZATION) IS A POPULAR STRATEGY FOR SIMPLIFYING SOFTWARE AND REDUCING
 * BUGS. IT'S ALSO A CORE ASPECT OF FUNCTIONAL PROGRAMMING, WHERE MUTABLE
 * STATE IS AVOIDED AND FUNCTIONS ARE TREATED AS DATA. LINQ IS INSPIRED BY
 * THIS PRINCIPLE.
 *
 * IN ORDER TO 'MODIFY' AN IMMUTABLE OBJECT, YOU MUST CREATE A NEW ONE AND
 * COPY OVER THE DATA WHILE INCORPORATING YOUR MODIFICATIONS - THIS IS CALLED
 * NONDESTRUCTIVE MUTATION.
 */

public record FirstRecord();